### ISSUE TITLE
[QA] Token shows as not registered after registering it

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#1248]
Preconditions:
Metamask wallet connected at sending From section
Solflare wallet at sending To section
USDC asset available for the Base Goerli network

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 118.0.5993.88

Tested from: https://deploy-preview-1174--wormhole-connect.netlify.app/# and https://wormhole-foundation.github.io/example-token-bridge-ui/#/register

Steps:
1. Prepare to send 0.001 USDC (Base Goerli) from Base Goerli to Solana
2. Observe that message "This token is not registered, you must [register](https://wormhole-foundation.github.io/example-token-bridge-ui/#/register) it before you continue. Newly registered tokens will not have liquid markets." is shown
3. Click on button "register"
4. Enter Source chain Base Goerli
5. Connect Metamask wallet
6. Paste in the USDC contract address ( 0xF175520C52418dfE19C8098071a252da48Cd1C19 )
7. Click Next
8. Select Solana Network\Connect Solflare wallet
9. Click Next
10. Click on Attest
11. Observe that token shows as registered
12. Return to https://deploy-preview-1174--wormhole-connect.netlify.app/# and refresh the page
13. Repeat step 1
14. Observe

Actual result: USDC (Base Goerli) for transaction Base Goerli to Solana shows as attested, but when returning to Wormhole-connect page to make the transaction, the token shows again as not registered

Expected result: Token is registered and user can create a transaction USDC (Base Goerli) from Base Goerli to Solana

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/39e97279-ab63-40a6-bbb3-df1953b4405f

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/43968f9e-0946-49e5-aace-fd986d6d03a0

**Comment by tsadovska** [comment]
Issue is also reproducible with Phantom wallet. Token is shown as registered, but after returning to transaction warning to register token does not disappear. 

Link in Step 3 "Send attestation": [Basescan](https://goerli.basescan.org/tx/0xaedc1cd533c5762329e7243340050edda4a2ed3d958905a72e93d33023c2ec6d)
Link in Step 4 "Create wrapped token": [Solscan](https://solscan.io/tx/2f2o9jxdbEKsWebR8y4P5n5NoPswS1oX5NKcEb83xvFcx5UsdjwpNHj1A3Uy6ZtT36mQLMUFyEZ9AJeuP3SKSXfK?cluster=devnet)

![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/b7e732c0-1a5b-4e6b-925c-fb499a9b9c69)


![image](https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e91e6e46-97a5-4789-9b5b-70d1981ea2a9)

**Comment by kev1n-peters** [comment]
Should be resolved when https://github.com/wormhole-foundation/wormhole/pull/3550 is merged and connect is updated with the latest wormhole SDK

**Comment by AigaD** [comment]
Token shows as registered, but again user is asked to register it for the transaction
tBTC from Solana (Phantom) to Sei (Leap)
Tested from: https://wormhole-connect.netlify.app/# and https://wormhole-foundation.github.io/example-token-bridge-ui/#/register
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e3276e1a-66a3-4d4a-8897-3c85e6640a22

**Comment by AigaD** [comment]
Issue is still reproducible.
Tested from: https://deploy-preview-1317--wormhole-connect.netlify.app/
Registered tBTC token ( 6DNSN2BJsaPFdFFc1zP37kkeNe4Usc1Sqkzr9C9vPWcU ) from https://wormhole-foundation.github.io/example-token-bridge-ui/#/register that showed as success, but when returning to Wormhole-connect screen, token showed as not registered.
Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/2dc1bb9d-c6ec-4a9a-bbee-c976476b2c24

**Comment by AigaD** [comment]
Transaction USDC (BaseGoerli) from [Base Goerli](https://goerli.basescan.org/tx/0x72a2658968764bc7ed649bf8b01b723375f7c9090e6ba7e13b39e764c79f49bc) to[ Solana](https://explorer.solana.com/tx/92xyJ3ZLohxbdJAaUZ6Hd1JbcijEdFqSmsLn8q6Hmq8fGSZzbCfcoPdBXdNvxx2BnKrydrT4hJcpjNJMCCbfH5v?cluster=devnet) tested OK.
Tested from: https://deploy-preview-1317--wormhole-connect.netlify.app/
Attachment:
![Screenshot 2023-12-12 at 17 59 53](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/d709659d-ab2f-43a8-ab55-cd452be3f3a3)

**Comment by AigaD** [comment]
Re-opening the ticket.
Tested from: https://wormhole-connect.netlify.app/#
For transaction USDC from Mumbai to Solana (Solong) user is asked to register USDC token (0x9999f7Fea5938fD3b1E26A12c3f2fb024e194f97) after registering it and returning to transaction it still shows as not registered.
Reproduced also for transaction USDC from Arbitrum to Solana (Nightly)
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/aa7110fd-8a46-4024-99e9-9427c9a02161

**Comment by AigaD** [comment]
Re-opening ticket.
Tested from: https://wormhole-connect.netlify.app/# and https://wormhole-foundation.github.io/example-token-bridge-ui/#/register
USDC (Goerli) (0x850bFeC40aFe1ABCd867D7BBA61A8398563f3e6E) for transaction Sepolia (Metamask) to Aptos (Petra) shows as still not registered when returning to transaction (after page re-fresh) after registering the asset

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/11d4ae8a-5f7c-4e7c-af11-a1bac9ff54a3


![Screenshot 2024-02-29 at 10 22 05](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/35177c35-12f8-465d-a577-a4ee4068d402)

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/e10dc401-e214-421a-8094-a5f68692f54e

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
USDT (0x9aE3161B9ADb36C534881BE5510300F8c89003dA) token from Klaytn (Rabby) to Aptos (Martian) shows as not registered after user has registered it at https://wormhole-foundation.github.io/example-token-bridge-ui/#/register

Attachment:


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/08682c59-ec86-4c31-958b-198338da238c

![Screenshot 2024-03-07 at 17 22 48](https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5fcaae59-16c6-4afd-ad4c-d3d96c1f8b5d)

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
USDC (0xb8656a09a489819f07c444cb4a4a61a3b482a5ea994fd71b0a643ffc1c2f2dd0::iusdc::IUSDC) asset for transfer from Sui (Sui wallet) to Aptos (Rise wallet) shows as not registered. After registering it, message is still shown to register the asset.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/bf9a5e6f-2d06-4dbf-baca-83ace8cb847d

**Comment by AigaD** [comment]
Tested from: https://wormhole-connect.netlify.app/#
USDT token (0x32eF19C4b3DF65a24972A489e70AdDef5E54262C) for transaction from Fantom to Alfajores shows as not registered after registering it.
Attachment:
<img width="1049" alt="Screenshot 2024-04-25 at 09 06 28" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/6d19645a-53a6-4259-a3bc-5dd823f234ce">
<img width="1045" alt="Screenshot 2024-04-25 at 09 06 17" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/4a58778b-0e12-47a3-802d-a26072a7863b">

**Comment by tsadovska** [comment]
Rechecked scenarios mentioned in the ticket:
* USDC asset registration for tx Base Goerli -> Solana: Goerli is deprecated and Sepolia is not configured yet, see ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1623
* tBTC asset registration for tx Solana -> Sei: ticket https://github.com/wormhole-foundation/wormhole-connect/issues/2002
* USDC asset registration for tx Mumbai to Solana: blocked by https://github.com/wormhole-foundation/wormhole-connect/issues/1958, Mumbai is deprecated.
* USDC (Sepolia) asset registration for tx Sepolia -> Aptos: asset is successfully registered
* USDT asset registration for tx Klaytn -> Aptos: ticket https://github.com/wormhole-foundation/wormhole-connect/issues/1719
* USDC (Sepolia) asset registration for tx Sui (Sui) -> Aptos (Rise): asset is successfully registered
* USDT (Sepolia) token registration: ticket https://github.com/wormhole-foundation/wormhole-connect/issues/2187

Ticket is closed.
