### ISSUE TITLE
[QA] [Redesign] Some options from "Select a network" dropdown cannot be selected on small screens

### ISSUE THREAD

**Issue by tsadovska** [wormhole-foundation/wormhole-connect#2300]
## Describe the current behavior in detail
Checked on [netlify mainnet](https://wormhole-connect-mainnet.netlify.app/?config=N4KABGCmB2BuBcYDkBbAhgS2tSAXJANOGAK4DOkASpACaRkYDm0iuATiZCAL5A%3D%3D) with macOS Sonoma 14.5 and Google Chrome Version 126.0.6478.183 (Official Build) (arm64).

Custom config:
```
{
  env: 'mainnet',
  useRedesign: true
}
```

Steps:
1. Open dropdown menu in From section
2. Change screen size
3. Check "Other", "Fantom" and other option can be selected

Actual result: Options cannot be selected.
Expected result: Options can be selected.

## Notes/ Attachments

https://github.com/user-attachments/assets/b0354661-2e50-4b29-906f-ffd01e47ea2d

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/b1f3c5115d/. Checked on iPhone 11 Pro. 

"Other" button is not visible when using mobile in Portrait mode. 


https://github.com/user-attachments/assets/e209897c-aecc-45b9-8bd8-d962c5a490df

"Other" button is visible only when using device in landscape mode. 


![Screenshot 2024-09-13 at 20 50 28](https://github.com/user-attachments/assets/434f9c4c-41cc-4661-912f-b7255a355c2b)

**Comment by yuli-ferna** [comment]
This should be fixed! https://preview.portalbridge.com/b1f3c5115d/
@tsadovska 

<img width="502" alt="image" src="https://github.com/user-attachments/assets/a0f6fc4a-5c56-4189-b37e-d60675bae5bc">

Issue related: https://github.com/wormhole-foundation/wormhole-connect/issues/2597

**Comment by Wesleyleung** [comment]
This issue is improved but the dropdown menu for chain + token selection still gets cut off. See the right side of the screenshot below (using iPhone 15)

![IMG_9176](https://github.com/user-attachments/assets/084f8b82-cec5-41bd-bb87-81fcd736f8ef)
