### ISSUE TITLE
[QA] Wrapped assets are not displayed for Mantle network on deploy-preview-2985

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#3139]
## Describe the current behavior in detail
Environment:

- OS: macOS Sequoia 15.2
- Wallets: MetaMask
- Browser: Google Chrome Version 131.0.6778.205 (Official Build) (x86_64)
- [Netlify preview](https://deploy-preview-2985--wormhole-connect-mainnet.netlify.app/?config=N4KABGDGD2CWB2BxAppA1tAggB1gaWQE8AuMAcgGFEBaAUQBEAZAMwBdGBDAMVoHUBNAI4AtAHIBnAAoA1AO4AhepjwVaZADTgwAJ2gBXVsnGkA2gFkOhDvABK%2BwwGVeASS4AVdWAB0P%2BrS6YAKqMbgD6NgDygW60DgC6IAC%2BQA%3D)

Steps to reproduce:

1. Select Mantle as source chain
2. Connect MetaMask wallet
3. Open "From" section and check available assets

Actual result: Only MNT and Sui assets are displayed in the list, other assets are not displayed.
Expected result: All available assets are displayed in the list.

## Attachments/Notes
Similar tickets - #3138, #3141

<img width="1697" alt="image" src="https://github.com/user-attachments/assets/4497be1e-efa4-4af3-ad74-a837dbd0d845" />

**Comment by artursapek** [comment]
should be fixed in deploy preview

**Comment by agodlevska** [comment]
Issue is still reproducible on https://deploy-preview-2985--wormhole-connect-mainnet.netlify.app/.
Only MNT asset is displayed in the list, other assets are not displayed.

Attachment:
<img width="586" alt="Screenshot 2025-01-08 at 11 56 10" src="https://github.com/user-attachments/assets/16ce6e29-181e-4bda-8972-1d5ee9bcc497" />

**Comment by agodlevska** [comment]
Issue has been fixed. 
All available assets are displayed in the list.

Closing the ticket. 

Attachment:
<img width="1440" alt="Screenshot 2025-01-08 at 17 02 28" src="https://github.com/user-attachments/assets/21d876b4-817c-4e69-af2e-1ab99ef829f1" />
