### ISSUE TITLE
[QA] Wrapped assets are not displayed for Scroll network on deploy-preview-2985

### ISSUE THREAD

**Issue by agodlevska** [wormhole-foundation/wormhole-connect#3141]
## Describe the current behavior in detail
Environment:

- OS: macOS Sequoia 15.2
- Wallets: MetaMask
- Browser: Google Chrome Version 131.0.6778.205 (Official Build) (x86_64)
- [Netlify preview](https://deploy-preview-2985--wormhole-connect-mainnet.netlify.app/?config=N4KABGDGD2CWB2BxAppA1tAggB1gaWQE8AuMAcgGFEBaAUQBEAZAMwBdGBDAMVoHUBNAI4AtAHIBnAAoA1AO4AhepjwVaZADTgwAJ2gBXVsnGkA2gFkOhDvABK%2BwwGVeASS4AVdWAB0P%2BrS6YAKqMbgD6NgDygW60DgC6IAC%2BQA%3D)

Steps to reproduce:

1. Select Scroll as source chain
2. Connect MetaMask wallet
3. Open "From" section and check available assets

Actual result: Only ETH asset is displayed in the list, other assets are not displayed.
Expected result: All available assets are displayed in the list.

## Attachments/Notes
Similar tickets - #3138, #3139

<img width="1704" alt="image" src="https://github.com/user-attachments/assets/7206f12e-62f7-40fc-99b9-3178a876031f" />

**Comment by artursapek** [comment]
should be fixed in deploy preview

**Comment by agodlevska** [comment]
Issue is still reproducible on https://deploy-preview-2985--wormhole-connect-mainnet.netlify.app/.
Only ETH asset is displayed in the list, other assets are not displayed.

Attachment:
<img width="636" alt="Screenshot 2025-01-08 at 11 56 29" src="https://github.com/user-attachments/assets/d14bb416-f29c-4f19-a176-553ce98490e5" />

**Comment by agodlevska** [comment]
Issue has been fixed.
All available assets are displayed in the list.

Closing the ticket.

Attachment:
<img width="1440" alt="Screenshot 2025-01-08 at 17 02 19" src="https://github.com/user-attachments/assets/ba740ecd-1d99-40bc-b7ab-c66ba82378e7" />
