### ISSUE TITLE
[QA]Glitch with warning messages

### ISSUE THREAD

**Issue by AigaD** [wormhole-foundation/wormhole-connect#952]
Preconditions: 
Metamask wallet connected

Environment: MacBook Pro, macOS Ventura 13.0.1, Chrome Version 115.0.5790.170

Tested from: https://feature-configurable-routes--wormhole-connect.netlify.app/ 

Scenario 1
Steps:
1. Connect Fuji Network at sending From section
2. Connect Moonbase Network at sending To section
3. Click on Assets and select Avax
4. In the amount field start typing 0.02
5. Observe the warning message shown below sending To section

Actual result: For a brief moment message "No bridge or swap route available for selected tokens" is shown

Expected result: No warning message is shown for tokens that have available swap route

Attachment:

<img width="1183" alt="Screenshot 2023-09-12 at 12 09 27" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/530ee341-8efa-4cfb-8cd3-38f310471a60">

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/689c144b-4b06-4872-a630-264d672f6be3

Scenario 2
Steps:
1. Connect Fantom Network at sending From section
2. Connect Sui Network at sending To section
3. Click on Assets and select FTM
4. In the amount field start typing 0.02
5. Observe the warning message regarding minimum amount

Actual result: Minimum amount warning message glitches

Expected result: Minimum amount warning message is shown and stays until user takes next action

Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/f3c6e4fb-cc5b-4ed4-992e-1169c8264d11

**Comment by AigaD** [comment]
Reproducible from: https://cctp-only--wormhole-connect.netlify.app/#
When sending USDC asset from Arbitrum message "No bridge or swap route available for selected tokens" is shown
And https://latest--wormhole-connect.netlify.app/ when 0.01 MATIC was sent from Polygon to BSC
Attachment:
<img width="1162" alt="Screenshot 2023-09-14 at 11 02 58" src="https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c8b76c08-65aa-46db-b0df-daa52b04d857">

**Comment by AigaD** [comment]
Minimum amount warning message shown for a brief moment for TX from Sei to Fantom
Tested from: https://latest--wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/c109a79f-04ab-43d2-b0d3-916eb63667e2

**Comment by derpy-duck** [comment]
The glitch from the second video ( Screen.Recording.2023-09-12.at.12.39.44.mov) is now resolved - that was the P1 (probably P0) issue.

I think now this should be brought down to P2 probably? The only issue now is the brief display of the warning message

**Comment by tonyjin** [comment]
I can confirm this issue still exists and does not on mainnet, which makes this a regression. We should try our best to not introduce regressions, so I wouldn't drop this to a P2.

**Comment by AigaD** [comment]
Reproduced also from: https://deploy-preview-907--wormhole-connect.netlify.app/
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/5ab6a768-9425-4c2d-bd9f-8555e993bc95

**Comment by tsadovska** [comment]
Warning messages "No associated token account exists for your wallet on Solana. You must create it before proceeding." and "No bridge or swap route available for selected token" are shown for a brief moment.


Checked on https://deploy-preview-907--wormhole-connect.netlify.app/ [Testnet].

Steps:
1. Select BSC in From section
2. Select Solana in To section
3. Connect Metamask in From section
4. Connect Backpack in To section
5. Prepare to send 0.01 BNB
6. Observe warning messages

https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/f7ed4ad0-8a8b-43e2-8c39-baa12f7446d3

**Comment by AigaD** [comment]
Tested OK.
Tested from:

- https://deploy-preview-1005--wormhole-connect.netlify.app/ (Mainnet)
- https://deploy-preview-1014--wormhole-connect.netlify.app/ (Testnet)
Message "No bridge or swap route available for selected tokens" is not shown

**Comment by AigaD** [comment]
Reopening the issue as there is a glitch with minimum amount being shown for a moment and then disappearing.
In example transaction from Sui to Base
Tested from: https://deploy-preview-1029--wormhole-connect.netlify.app/#
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/318a42ef-bf48-4722-a38d-9204a603864b


https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/96b5b71a-29e3-46a1-b1d9-2b5d2b146878

**Comment by tsadovska** [comment]
Issue is reproducible on https://deploy-preview-1029--wormhole-connect.netlify.app/ [Mainnet] when sending FTM from Fantom (Metamask) to Solana (Phantom). Warning message "No associated token account exists for your wallet on Solana. You must create it before proceeding." is shown when user wants to send 5 FTM and is not displayed when amount is increased to 6 USDT.


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/48d1b16a-2b1f-47fb-8902-0f523243794f

**Comment by evan-gray** [comment]
While the latest couple comments aren't exactly bugs (the amount was too small, then large enough / the amount was large enough to be relayed, but then not large enough so the routes switched). Perhaps the state update shouldn't trigger until the field loses focus.

**Comment by AigaD** [comment]
Reproduced from: https://deploy-preview-1058--wormhole-connect-mainnet.netlify.app/#
When changing asset amount for SUI that would be needed for One transaction route and Two transaction route
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/78d67b20-a0d3-4c8e-8066-0c97a7b2caac

**Comment by tsadovska** [comment]
Issue is reproducible on https://preview.portalbridge.com/92b0dfd6a1/usdc-bridge/ [Mainnet] with following scenario:

1. Prepare to send 4 USDC (Avalanche) from Avalanche (Metamask) to Base (Metamask)
2. Change amount to 2 
3. Observe

Minimum amount warning message is shown for a brief moment. Amount on warming message changes from 2.1 to 0. 


https://github.com/wormhole-foundation/wormhole-connect/assets/10746654/e372e9e1-7118-42de-abf1-10f6ccf5669d

**Comment by AigaD** [comment]
Reproduced also from: https://wormhole-connect.netlify.app/#
Minimum amount message is shown for a moment with changing amount
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/93cf83c1-0160-4ebd-b04b-af6a919e9550

**Comment by AigaD** [comment]
Tested from: https://deploy-preview-1372--wormhole-connect-mainnet.netlify.app/
Before each transaction, message "No bridge or swap route available available for selected tokens" is shown
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/14b7a51c-d60a-4aae-a4a5-e60abc3ffbc1

**Comment by AigaD** [comment]
Re-opening the ticket.
Tested from: https://wormhole-connect.netlify.app/#
Message "No bridge or swap route available available for selected tokens" is shown for transaction WBTC from Goerli to Aptos, before entering the amount, after entering the amount message disappears, token registration is required.
Attachment:

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/0994f266-a749-40be-ab5a-9a11872ab7e8

https://github.com/wormhole-foundation/wormhole-connect/assets/91047061/df6dee17-8e0e-4f94-a6e9-aa224d8cdf7e

**Comment by artursapek** [comment]
bleh, thanks @AigaD. I was unable to reproduce the original video in the post. I'll see if I can fix this today.
